### PR TITLE
Switch to kleaf, update build environment to android14-6.1-lts

### PR DESCRIPTION
**Pull request by hmtheboy154**

### CODE REVIEW

**Comment by KonstaT** [comment]
Thanks. I've been postponing switching to bazel kernel build for various reasons. Eventually it will likely be required to build newer kernel version but until then, I'm not so sure that I want to switch. Don't be too disappointed if this doesn't happen before android15-6.6-lts.

I've had patches ready for this nearly a year but gave this another try. Main reason why this is still a no go for me is because I can't get bazel build to respect `CONFIG_LOCALVERSION_AUTO` being set. This currently produces kernel tagged as `6.1.78-maybe-dirty-v8` which is unacceptable to me. :) With dist build and `--config=release` set I can get `6.1.78-v8` but I'd still want the git HEAD tagged (i.e. `6.1.78-v8-g{HEAD-COMMIT-SHA1}`). There are other minor annoyances as well.

Some other notes/general thoughts.
- I'd want separate targets that only build the defconfig (i.e. relate to undocumented but very handy https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/build.config.rpi5.defconfig). I want to keep the full defconfigs up-to-date after each merge from raspberry and/or aosp upstreams.
- BUILD.bazel has been updated since the revert. Should be updated to match android14-6.1-lts to avoid future merge conflicts before adding the rpi targets.
- Add all the rpi configs in one place in BUILD.bazel (after the last device supported in AOSP `fips140`). Follow the same structure as the existing devices.

**Comment by hmtheboy154** [comment]
> Thanks. I've been postponing switching to bazel kernel build for various reasons. Eventually it will likely be required to build newer kernel version but until then, I'm not so sure that I want to switch. Don't be too disappointed if this doesn't happen before android15-6.6-lts.

it's fine, we can just slowly prepare for the switch

> 
> I've had patches ready for this nearly a year but gave this another try. Main reason why this is still a no go for me is because I can't get bazel build to respect `CONFIG_LOCALVERSION_AUTO` being set. This currently produces kernel tagged as `6.1.78-maybe-dirty-v8` which is unacceptable to me. :) With dist build and `--config=release` set I can get `6.1.78-v8` but I'd still want the git HEAD tagged (i.e. `6.1.78-v8-g{HEAD-COMMIT-SHA1}`). There are other minor annoyances as well.

I can't seems to replicate this and instead if I build with `--config=release` or `--config=fast --config=stamp` I get `6.1.78-gec65163bb24d-dirty-v8`. It still have `-dirty` tag (maybe because I have uncommited files) but at least there is the SHA1 HEAD.

Maybe Google fixed it ?
> 
> Some other notes/general thoughts.
> 
> * I'd want separate targets that only build the defconfig (i.e. relate to undocumented but very handy https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/build.config.rpi5.defconfig). I want to keep the full defconfigs up-to-date after each merge from raspberry and/or aosp upstreams.

Seems like we can do ` tools/bazel run //common:rpi5_config` however what bazel generate seems stripped down too much. I guess we can do like the documentation 
https://android.googlesource.com/kernel/build/+/refs/heads/main/kleaf/docs/build_configs.md#post_defconfig_cmds

Create a `kernel_build_config` which has a `genrule` target as src, put it into BUILD.bazel to run it manually or only run when the kernel build target is done.

> * BUILD.bazel has been updated since the revert. Should be updated to match android14-6.1-lts to avoid future merge conflicts before adding the rpi targets.

I didn't notice this 😅


> * Add all the rpi configs in one place in BUILD.bazel (after the last device supported in AOSP `fips140`). Follow the same structure as the existing devices.

I think that what I made are already follow the structure as I directly use `build_config_to_bazel.py`. However to save time I'd suggest one small thing and that is do not change  `base_kernel = None,` to `base_kernel = ":kernel_aarch64",` . Build kernel_aarch64 target will just waste you extra time.

**Comment by KonstaT** [comment]
> I can't seems to replicate this and instead if I build with `--config=release` or `--config=fast --config=stamp` I get `6.1.78-gec65163bb24d-dirty-v8`. It still have `-dirty` tag (maybe because I have uncommited files) but at least there is the SHA1 HEAD.

This was because I had locally cloned the kernel repository to `common` directory instead of syncing it through the manifest. I think the bazel build env pulls the stamp from the `.repo` dir somehow. It also changes the order of the git HEAD and what's set in `CONFIG_LOCALVERSION` (e.g. from `6.1.78-v8-gc00f75404409` to `6.1.78-gc00f75404409-v8`). Not that it matters, just an observation that it doesn't something strange with the stamps.

I think `--config=fast --config=stamp` is what I want to go with. `--config=release` creates a separate bazel workdir and needs a really long relative path for `CONFIG_EXTRA_FIRMWARE_DIR`. On `android15-6.6` the workdir is somewhere at `/tmp` so you can't even make a relative path for the firmware.

> Seems like we can do `tools/bazel run //common:rpi5_config` however what bazel generate seems stripped down too much. I guess we can do like the documentation
> https://android.googlesource.com/kernel/build/+/refs/heads/main/kleaf/docs/build_configs.md#post_defconfig_cmds

> Create a `kernel_build_config` which has a `genrule` target as src, put it into BUILD.bazel to run it manually or only run when the kernel build target is done.

Seems complicated. I have created a simple `kernel_build` target that generates the defconfig. It can't merge the configs but that's usually only needed when bringing up a new kernel version.

I have this ready on `android14-6.1-lts` and `android15-6.6` based on my older patches. Will push the source and close this PR later this week. The manifest/docs PR needs an update to use `--config=fast --config=stamp` but I can amend that as well.

**Comment by hmtheboy154** [comment]
> `--config=release` creates a separate bazel workdir and needs a really long relative path for `CONFIG_EXTRA_FIRMWARE_DIR`. On `android15-6.6` the workdir is somewhere at `/tmp` so you can't even make a relative path for the firmware.

Yea so seems like they make a `container` or `workspace` to build it and I started to think maybe you want to go for `--config=release` and then symlink `vendor/brcm/proprietary` to `common/` and edit `CONFIG_EXTRA_FIRMWARE_DIR`. But instead you go for `--config=fast --config=stamp` which is great.

> Will push the source and close this PR later this week. 

I hope you can get it done soon as the latest source doesn't seem to boot into the UI.

> The manifest/docs PR needs an update to use `--config=fast --config=stamp` but I can amend that as well.

If you want I can edit my manifest PR to `--config=fast --config=stamp` now and we can merge it when you update the kernel source.

**Comment by KonstaT** [comment]
Closing as this is now implemented on `android-14.0` and `android-15.0` branches.

> Yea so seems like they make a `container` or `workspace` to build it and I started to think maybe you want to go for `--config=release` and then symlink `vendor/brcm/proprietary` to `common/` and edit `CONFIG_EXTRA_FIRMWARE_DIR`. But instead you go for `--config=fast --config=stamp` which is great.

That would no longer work on `android15-6.6` as the workdir is at `/tmp` (i.e. as in root of the host machine so any symlink would need to have absolute path).

> I hope you can get it done soon as the latest source doesn't seem to boot into the UI.
 
Doesn't seem like a kernel issue. AOSP build from up-to-date Raspberry Vanilla sources should boot to UI just fine.

**Comment by hmtheboy154** [comment]
> Doesn't seem like a kernel issue. AOSP build from up-to-date Raspberry Vanilla sources should boot to UI just fine.

Yea about that.....

[tombstone_49.txt](https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/files/15176350/tombstone_49.txt)

It's not kernel issue for sure. It just that the OS doesn't boot when I built it. But seems like you pushed new changes now. I'll test it later

**Comment by KonstaT** [comment]
> > Doesn't seem like a kernel issue. AOSP build from up-to-date Raspberry Vanilla sources should boot to UI just fine.
> 
> Yea about that.....
> 
> [tombstone_49.txt](https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/files/15176350/tombstone_49.txt)
> 
> It's not kernel issue for sure. It just that the OS doesn't boot when I built it. But seems like you pushed new changes now. I'll test it later

https://github.com/raspberry-vanilla/android_local_manifest/issues/76#issuecomment-2077481855

**Pull request closed without merging**
